version: '3'

volumes:
  db-data:

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dev/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - db

  api:
    build:
      context: .
      dockerfile: ./dev/docker/api/Dockerfile
    volumes:
      - ./src/api:/app
    working_dir: /app
    tty: true
    environment:
      - DB_NAME=hacobi
      - DB_USER=hacobi
      - DB_PASSWORD=hacobi
      - DB_HOST=db
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hacobi
      MYSQL_USER: hacobi
      MYSQL_PASSWORD: hacobi
    volumes:
      - db-data:/var/lib/mysql
  
